// <auto-generated />
namespace MvcApplicationCustomModelBinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removecolunaid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecolunaid));
        
        string IMigrationMetadata.Id
        {
            get { return "201303131741339_removecolunaid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
